# Generated by Django 3.0.3 on 2020-08-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopuser', '0002_shopuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='password',
            field=models.CharField(max_length=128, verbose_name='비밀번호'),
        ),
    ]
