# Generated by Django 3.0.3 on 2020-02-19 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
    ]
